### ISSUE TITLE
Can't read image files.

### ISSUE THREAD

**Issue by larobitrumpet** [KingOfScience/Checkers-Game#1]
When trying to run `java game.CheckersMain`, I get a `javax.imageio.IIOException: Can't read input file!` error. It appears that the reason for this is that `CheckersMain.java` is looking for `blackKing.png` and `redKing.png` when neither of those files are present. `CheckersMain.java` is also looking for `'Red Checkered.png'` and `'Black Checkered.png'` when those files don't exists, but `'Red Checkered.jpg'` and `'Black Checkered.jpg'` are present.

**Comment by KingOfScience** [comment]
Hey! Yeah that because I used absolute paths in the code. I believe its
fixed now?

**Comment by KingOfScience** [comment]
Changed the files paths to relative paths, should work anywhere now. If not I'll change it to URL instead of Image.
